#!/bin/bash

if [ $# != 1 ];
then
    >&2 echo -e "USAGE:\n\t$0 <FILE>"
    exit 1
fi

FILE=$1
FILENAME=$(basename "$1")
TMPFILE="/tmp/${FILENAME}"

cat "test/sema/setup.sql" "${FILE}" > "${TMPFILE}"
build_debug/bin/check --ast "${TMPFILE}"
echo -e "\n--------------------\n"
echo "${TMPFILE}:"
cat -n "${TMPFILE}"
