#!/bin/bash

has_physical_tabs()
{
    ! perl -nle "exit 1 if /^\+.*\t/" $1
}

has_trailing_whitespaces()
{
    ! perl -nle "exit 1 if /^\+.*\s$/" $1
}

COMMIT_PASSED=1
for f in $(git diff --staged --name-only);
do
    if has_physical_tabs $f; then
        COMMIT_PASSED=0
        >&2 echo "error: file '$f' introduces physical tabs"
    fi
    if has_trailing_whitespaces $f; then
        COMMIT_PASSED=0
        >&2 echo "error: file '$f' introduces trailing white spaces"
    fi
done

if [[ $COMMIT_PASSED -eq 0 ]]; then
    >&2 echo "commit rejected"
    exit 1
fi

exit 0
